id: P008215
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12432
  title: འཕགས་མ་སྒྲོལ་མའི་མེ་ཏོག་ཕྲེང་བ་འཛིན་པའི་བསྟོད་པ།
  author: ''
  volumes:
    ef0e3edb446f428e8ee1560685b265a7:
      image_group_id: I1KG12466
      title: ''
      volume_number: 1
      total_pages: 75
      base_file: v001.txt
