id: I3B4F737B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:49:11+00:00'
last_modified: '2022-06-09T05:18:02.084149+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12432
  title: འཕགས་མ་སྒྲོལ་མའི་མེ་ཏོག་ཕྲེང་བ་འཛིན་པའི་བསྟོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFA5:
      image_group_id: I1KG12466
      title: ''
      total_pages: 75
      order: 1
      base_file: FFA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
